name: Bitcoin Container Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build
      run: docker build -t bitcoin --build-arg BITCOIN_VERSION="${{ env.BITCOIN_VERSION }}" ./docker 
    - name: Tags
      run: |
        docker tag bitcoin ${{ secrets.DOCKER_HUB_USER }}/bitcoin:${{ github.sha }}
        docker tag bitcoin ${{ secrets.DOCKER_HUB_USER }}/bitcoin:latest
    - name: Push
      run: |
        docker push ${{ secrets.DOCKER_HUB_USER }}/bitcoin:${{ github.sha }}
        docker push ${{ secrets.DOCKER_HUB_USER }}/bitcoin:latest

